import fs from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import url from 'node:url';

const ROOT: string = url.fileURLToPath(new URL('..', import.meta.url));

const fromRoot = ((...segments: string[]): string => path.resolve(ROOT, ...segments));

const rel = ((path_: string): string => (path.relative(ROOT, path_) || path_));

// ==================================================
// Banner
// ==================================================

type CommentStyle = ('line' | 'html');

const bannerLines = ((script: string): string[] => [
  `Generated by scripts/${script} — DO NOT EDIT.`,
  'Run `bun run gen` to regenerate. CI fails if this file is stale.'
]);

const banner = ((
  script: string,
  style: CommentStyle = 'line'
): string => {
  const lines = bannerLines(script);

  if(style === 'html') {
    return `<!--\n${lines.map(line => `  ${line}`).join('\n')}\n-->`;
  }

  return [
    '/* eslint-disable */',
    '/* prettier-ignore */',
    ...lines.map(line => `// ${line}`)
  ].join('\n');
});

// ==================================================
// Emit / check
// ==================================================

interface GeneratedFile {
  path: string;
  content: string;
}

type Generator = (() => Promise<GeneratedFile[]>);
type Mode = ('write' | 'check');
type EmitStatus = ('written' | 'unchanged' | 'missing' | 'stale');

interface EmitResult {
  path: string;
  status: EmitStatus;
  detail?: string;
}

const truncate = ((
  line: string,
  max = 160
): string => ((line.length > max) ? `${line.slice(0, max)}...` : line));

const firstDifference = ((
  expected: string,
  actual: string
): string => {
  // Both sides are newline-terminated after normalization, so `split()` leaves
  // a trailing empty element that would otherwise mask the end-of-file marker.
  const dropTrailing = ((lines: string[]): string[] => ((lines.at(-1) === '') ? lines.slice(0, -1) : lines));

  const a = dropTrailing(expected.split('\n'));
  const b = dropTrailing(actual.split('\n'));

  for(let i = 0; i < Math.max(a.length, b.length); i++) {
    if(a[i] !== b[i]) {
      return [
        `first difference at line ${i + 1}:`,
        `  expected: ${truncate(a[i] ?? '<end oif file>')}`,
        `  on disk:  ${truncate(b[i] ?? '<end of file>')}`
      ].join('\n');
    }
  }

  return 'files differ only in trailing whitespace';
});

/**
 * Normalization is applied to both sides of every comparison so that line
 * endings and trailing whitespace can never produce a spurious CI failure.
 */
const normalizeContent = ((input: string): string =>
  `${input
    .replaceAll('\r\n', '\n')
    .replaceAll(/[ \t]+$/gm, '')
    .replace(/\n+$/, '')}\n`);

// eslint-disable-next-line max-lines-per-function, max-statements -- Clean.
const emit = (async(
  files: GeneratedFile[],
  mode: Mode
): Promise<EmitResult[]> => {
  const results: EmitResult[] = [];

  for(const file of files) {
    const expected = normalizeContent(file.content);

    let actual: (string | null) = null;
    try {
      // eslint-disable-next-line no-await-in-loop -- Safe.
      actual = normalizeContent(await fs.readFile(file.path, 'utf8'));
    } catch{
      // NO-OP.
    }

    if(actual === expected) {
      results.push({
        path: file.path,
        status: 'unchanged'
      });

      continue;
    }

    if(mode === 'check') {
      results.push(
        (actual === null)
          ? {
              path: file.path,
              status: 'missing'
            }
          : {
              path: file.path,
              status: 'stale',
              detail: firstDifference(expected, actual)
            }
      );

      continue;
    }

    // eslint-disable-next-line no-await-in-loop -- Safe.
    await fs.mkdir(path.dirname(file.path), {recursive: true});
    // eslint-disable-next-line no-await-in-loop -- Safe.
    await fs.writeFile(file.path, expected, 'utf8');

    results.push({
      path: file.path,
      status: 'written'
    });
  }

  return results;
});

// ==================================================
// Orchestration
// ==================================================

const runGenerators = (async(
  generators: Record<string, Generator>,
  mode: Mode
): Promise<EmitResult[]> => {
  const results: EmitResult[] = [];

  for(const [
    name,
    generate
  ] of Object.entries(generators)) {
    // eslint-disable-next-line @typescript-eslint/init-declarations -- Correct.
    let files: GeneratedFile[];
    try {
      // eslint-disable-next-line no-await-in-loop -- Safe.
      files = (await generate());
    } catch(err: unknown) {
      throw (new Error(`Generator "${name}" failed`, {cause: err}));
    }

    // eslint-disable-next-line no-await-in-loop -- Safe.
    results.push(...(await emit(files, mode)));
  }

  return results;
});

const STATUS_LABEL: Record<EmitStatus, string> = {
  written: 'wrote',
  unchanged: 'ok',
  missing: 'MISSING',
  stale: 'STALE'
};

/** Returns the intended process exit code. */
const report = ((
  results: EmitResult[],
  mode: Mode
): number => {
  for(const result of results) {
    process.stderr.write(`${STATUS_LABEL[result.status].padEnd(8)} ${rel(result.path)}\n`);

    if(result.detail) {
      for(const line of result.detail.split('\n')) {
        process.stderr.write(`         ${line}\n`);
      }
    }
  }

  const outOfDate = results.filter(r => ((r.status === 'stale') || (r.status === 'missing')));

  if((mode === 'check') && (outOfDate.length > 0)) {
    process.stderr.write(`\n${outOfDate.length} generated file(s) out of date. Run \`bun run gen\` and commit the result.\n`);

    return 1;
  }

  return 0;
});

// ==================================================
// CLI
// ==================================================

const parseMode = ((argv: string[] = process.argv.slice(2)): Mode => (argv.includes('--check') ? 'check' : 'write'));

/** True when the module at `url` was invoked directly, not imported. */
const isEntrypoint = ((url_: string): boolean => {
  const entry = process.argv[1];
  if(!entry) {
    return false;
  }

  return (url_ === url.pathToFileURL(path.resolve(entry)).href);
});

const runAsScript = (async(generate: Generator): Promise<void> => {
  const mode = parseMode();

  process.exitCode = report((await emit((await generate()), mode)), mode);
});

export type {
  CommentStyle,
  EmitResult,
  EmitStatus,
  GeneratedFile,
  Generator,
  Mode
};
export {
  banner,
  emit,
  firstDifference,
  fromRoot,
  isEntrypoint,
  normalizeContent,
  parseMode,
  rel,
  report,
  ROOT,
  runAsScript,
  runGenerators
};
